apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-a
  namespace: app-demo
  labels:
    migration.nginx.org/poc: enabled
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: demo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-svc
                port:
                  number: 80
